# Generated by Django 5.1 on 2024-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image', models.ImageField(upload_to='before_after/', verbose_name='عکس قبل')),
                ('after_image', models.ImageField(upload_to='before_after/', verbose_name='عکس بعد')),
            ],
        ),
        migrations.CreateModel(
            name='FilmFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frames/', verbose_name='عکس قاب')),
            ],
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('video', models.FileField(upload_to='reels/', verbose_name='ویدیو')),
                ('poster', models.ImageField(upload_to='reels/', verbose_name='پوستر')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='settings/', verbose_name='لوگو')),
                ('banner', models.ImageField(upload_to='settings/', verbose_name='بنر')),
                ('about_me', models.TextField(verbose_name='درباره من')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='لینک تلگرام')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
            ],
        ),
    ]
