# Generated by Django 5.1 on 2024-09-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='poster',
            field=models.ImageField(null=True, upload_to='reels/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_me',
            field=models.TextField(null=True, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='banner',
            field=models.ImageField(null=True, upload_to='settings/', verbose_name='بنر'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(null=True, upload_to='settings/', verbose_name='لوگو'),
        ),
    ]
