# Generated by Django 5.1 on 2024-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_reel_poster_alter_sitesetting_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='بنر'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='لوگو'),
        ),
    ]
