# Generated by Django 5.1 on 2024-09-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_sitesetting_about_me_alter_sitesetting_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_me_footer',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من در فوتر'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='working_img',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='عکس افتخار همکاری'),
        ),
    ]
